name: Run tests

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  run-tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10

      - name: Set script permissions
        run: chmod +x cypress/test.sh

      - name: Run test script
        run: bun run test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: cypress/results/index.html
